# Generated by Django 4.0.2 on 2022-02-20 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thumb', models.ImageField(upload_to='')),
                ('comment_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='authormodel',
            old_name='profile',
            new_name='profile_pic',
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BlogModel',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.authormodel'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='categories',
            field=models.ManyToManyField(to='blog.CategoryModel'),
        ),
    ]
