# Generated by Django 4.0.2 on 2022-02-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_rename_profile_authormodel_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
