# Generated by Django 4.0.3 on 2022-03-07 20:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postmodel_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='content',
            field=tinymce.models.HTMLField(default='test', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
