# Generated by Django 4.0.3 on 2022-03-12 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='_next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_post', to='blog.postmodel'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='_previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_post', to='blog.postmodel'),
        ),
    ]
