# Generated by Django 4.0.3 on 2022-03-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postmodel__next_postmodel__previous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='_next',
            new_name='pm_next',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='_previous',
            new_name='pm_previous',
        ),
    ]
