# Generated by Django 4.0.3 on 2022-03-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_commentmodel_name_alter_commentmodel_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='comment_count',
        ),
    ]
