# Generated by Django 4.0.3 on 2022-03-31 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_postmodel_view_count_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='author',
            field=models.ForeignKey(default='Sadat', on_delete=django.db.models.deletion.CASCADE, to='blog.authormodel'),
            preserve_default=False,
        ),
    ]
