# Generated by Django 4.0.3 on 2022-03-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_commentmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='author',
        ),
    ]
