# Generated by Django 4.0.3 on 2022-03-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_commentmodel_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='creator',
        ),
    ]
